schema_version: 1
name: jboss.container.eap.prometheus.runtime
version: '1.0'
description: Provides Prometheus JMX Exporter configuration and agent

modules:
  install:
  - name: jboss.container.prometheus
  - name: jboss.container.eap.prometheus.jmx-exporter-config
