schema_version: 1
name: jboss.container.eap.prometheus.config
version: '1.0'
description: Provides Prometheus JMX Exporter configuration

execute:
- script: configure.sh
  user: 185

modules:
  install:
  - name: jboss.container.prometheus.bash
  - name: jboss.container.eap.prometheus.jmx-exporter-config
